version: "3"

services:
  postgres:
    image: postgres
    env_file:
      - .env
    expose:
      - 5432
    ports:
      - "5432:5432"
    networks:
      - portal
      - gateway
    volumes:
      - porters-postgres:/var/lib/postgresql/data

  frontend:
    build:
      context: ./web-portal/frontend
    depends_on:
      - backend
    expose:
      - 3000
    ports:
      - "3000:3000"
    networks:
      - portal

  backend:
    build:
      context: .
    depends_on:
      - postgres
    expose:
      - 4000
    ports:
      - "4000:4000"
    networks:
      - portal

  gateway:
    build:
      context: ./gateway
    depends_on:
      - redis
      - postgres
    expose:
      - 9000
    ports:
      - "9000:9000"
    networks:
      - gateway
    env_file:
      - .env

  redis:
    image: redis:alpine
    env_file:
      - .env
    ports:
      - "6379:6379"
    networks:
      - gateway
    volumes:
      - porters-redis:/data

volumes:
  porters-postgres:
  porters-redis:

networks:
  portal:
    driver: bridge
  gateway:
