version: "3"

services:
  postgres:
    image: postgres
    env_file:
      - .env
    expose:
      - 5432
    ports:
      - "5432:5432"
    networks:
      - portal
      - gateway
    volumes:
      - porters-postgres:/var/lib/postgresql/data

  schema:
    build:
      context: ./services/postgres
    image: porters-schema:latest
    env_file:
      - .env
    networks:
      - portal
    command: tail -f /dev/null

  frontend:
    env_file:
      - .env
    build:
      context: ./web-portal/frontend
      args:
        API_ENDPOINT: ${API_ENDPOINT}
    depends_on:
      - backend
    expose:
      - 3000
    ports:
      - "3000:3000"
    networks:
      - portal

  backend:
    build:
      context: ./web-portal/backend
    depends_on:
      - postgres
    expose:
      - 4000
    ports:
      - "4000:4000"
    networks:
      - portal

  gateway:
    build:
      context: ./gateway
    depends_on:
      - redis
      - postgres
    expose:
      - 9000
    ports:
      - "9000:9000"
    networks:
      - gateway
    env_file:
      - .env

  redis:
    image: redis:alpine
    env_file:
      - .env
    ports:
      - "6379:6379"
    networks:
      - gateway
    volumes:
      - porters-redis:/data

  kit:
    image: ghcr.io/pokt-network/pocket-gateway-server:0.3.0
    volumes:
      - ./.env:/app/.env
    ports:
      - "8080:8080"
    env_file:
      - ./.kit.env
    networks:
      - gateway

  docs:
    build:
      context: ./docs
    expose:
      - 3005
    ports:
      - "3005:3005"
    networks:
      - docs
volumes:
  porters-postgres:
  porters-redis:

networks:
  portal:
    driver: bridge
  gateway:
  docs:
    driver: bridge
