version: '3'

services:
  frontend:
    build:
      context: ./web-portal/frontend
    depends_on:
      - backend
    expose:
      - "8000"
    networks:
      - portal
  backend:
    build:
      context: ./web-portal/backend
    depends_on:
      - postgres
    networks:
      - portal
  gateway:
    build:
      context: ./gateway
    depends_on:
      - redis
      - postgres
    ports:
      - "9000:9000"
    networks:
      - gateway
    env_file:
      - .env
  redis:
    image: redis:alpine
    env_file:
      - .env
    ports:
      - "6379:6379"
    networks:
      - gateway
    volumes:
      - porters-redis:/data
  postgres:
    image: postgres
    env_file:
      - .env
    ports:
      - "5432:5432"
    networks:
      - portal
      - gateway
    volumes:
      - porters-postgres:/var/lib/postgesql/data

volumes:
  porters-postgres:
  porters-redis:

networks:
  portal:
  gateway:
