# fly.toml app configuration file generated for porters-proxy-staging on 2024-04-03T20:23:41-05:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = 'porters-proxy'
primary_region = 'sea'

[build]

[deploy]
  strategy = 'canary'

[env]
  HOST = 'rpc.porters.xyz'
  ### SECRETS ###
  # DATABASE_URL = ...
  # PROXY_TO = ...
  # REDIS_URL = ...

[http_service]
  internal_port = 9000
  force_https = true
  auto_stop_machines = false 
  auto_start_machines = false
  processes = ['app']
  [[http_service.checks]]
    grace_period = '2s'
    interval = '30s'
    method = 'GET'
    timeout = '3s'
    path = '/health'

[[vm]]
  memory = '1gb'
  cpu_kind = 'shared'
  cpus = 1

[[metrics]]
  port = 9000
  path = "/metrics"
