default:
    @just --list

build:
    go install

test:
    go test ./...

run: build
    porters gateway

docker-build:
    docker build -t porters .

docker-run: docker-build
    docker run -d -p 9999:9999 porters

alias b := build
