# fly.toml app configuration file generated for porters-frontend-staging on 2024-04-04T20:17:36-05:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = 'porters-frontend-staging'
primary_region = 'sea'

[build.args]
  NEXT_PUBLIC_API_ENDPOINT = 'https://porters-backend-staging.fly.dev/'

[http_service]
  internal_port = 3000
  force_https = true
  auto_stop_machines = true
  auto_start_machines = true
  min_machines_running = 0
  processes = ['app']

[env]
  NEXT_PUBLIC_API_ENDPOINT = 'https://porters-backend-staging.fly.dev/'

[[vm]]
  memory = '1gb'
  cpu_kind = 'shared'
  cpus = 1
