app = 'porters-backend'
primary_region = 'sea'

[build]
  dockerfile = 'Dockerfile.fly'

[build.args]
  SCHEMA_VERSION = '0.0.1'

[env]
  ### SECRETS ###
  # DATABASE_URL = ...
  # ONEINCH_API_KEY = ...
  # OX_API_KEY = ...
  # RPC_KEY = ...
  PROM_URL = 'https://api.fly.io/prometheus/porters/api/v1/'

[[services]]
  internal_port = 4000
  protocol = 'tcp'
  auto_stop_machines = true
  auto_start_machines = true
  min_machines_running = 0
  [[services.ports]]
    handlers = ["http"]
    port = 4000
    force_https = false

[[vm]]
  memory = '1gb'
  cpu_kind = 'shared'
  cpus = 1
