app = 'porters-backend'
primary_region = 'sea'

[build]
  dockerfile = 'Dockerfile.fly'

[env]
  ### SECRETS ###
  # DATABASE_URL = ...
  # ONEINCH_API_KEY = ...
  # OX_API_KEY = ...
  # RPC_KEY = ...

[http_service]
  internal_port = 4000
  force_https = false
  auto_stop_machines = true
  auto_start_machines = true
  min_machines_running = 0
  processes = ['app']

[[vm]]
  memory = '1gb'
  cpu_kind = 'shared'
  cpus = 1
