# fly.toml app configuration file generated for porters-backend-staging on 2024-04-02T17:39:45-05:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = 'porters-backend-staging'
primary_region = 'sea'

[build]
  dockerfile = 'Dockerfile.fly'

[env]
  ### SECRETS ###
  # DATABASE_URL = ...
  # ONEINCH_API_KEY = ...
  # OX_API_KEY = ...
  # RPC_KEY = ...
  PROM_URL = 'https://api.fly.io/prometheus/porters-staging/api/v1/'

[http_service]
  internal_port = 4000
  force_https = true
  auto_stop_machines = true
  auto_start_machines = true
  min_machines_running = 0
  processes = ['app']

[[vm]]
  memory = '1gb'
  cpu_kind = 'shared'
  cpus = 1
