# fly.toml app configuration file generated for porters-redis-staging on 2024-04-02T20:50:19-05:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

# change app to -stage for staging
app = 'porters-redis'
primary_region = 'sea'

[build]
  image = 'redis:7'

[mounts]
  source = "redis_data"
  destination = "/data"

[[vm]]
  memory = '1gb'
  cpu_kind = 'shared'
  cpus = 1
