name: Fly Deploy Staging Backend
on:
    push:
        branches:
            - develop
        paths:
            - "web-portal/backend/**"
jobs:
    deploy:
        name: Deploy Staging Frontend
        runs-on: ubuntu-latest
        concurrency: deploy-group
        steps:
            - uses: actions/checkout@v4
            - uses: superfly/flyctl-actions/setup-flyctl@master
            - run: cd web-portal/backend
            - run: flyctl deploy  -c fly.staging.toml --remote-only
              env:
                  FLY_API_TOKEN: ${{ secrets.FLY_STAGING_API_TOKEN }}
