name: Fly Deploy Prod Backend
on:
    push:
        branches:
            - master
        paths:
            - "web-portal/backend/**"
jobs:
    deploy:
        name: Deploy Prod Backend
        runs-on: ubuntu-latest
        concurrency: deploy-group
        steps:
            - uses: actions/checkout@v4
            - uses: superfly/flyctl-actions/setup-flyctl@master
            - run: cd web-portal/backend && flyctl deploy -c fly.prod.toml --remote-only
              env:
                  FLY_API_TOKEN: ${{ secrets.FLY_PROD_API_TOKEN }}
