name: Fly Deploy Prod Docs
on:
    push:
        branches:
            - master
        paths:
            - "docs/**"
jobs:
    deploy:
        name: Deploy Prod Frontend
        runs-on: ubuntu-latest
        concurrency: deploy-group
        steps:
            - uses: actions/checkout@v4
            - uses: superfly/flyctl-actions/setup-flyctl@master
            - run:  cd docs && flyctl deploy  -c fly.prod.toml --remote-only
              env:
                  FLY_API_TOKEN: ${{ secrets.FLY_PROD_API_TOKEN }}
