name: Fly Deploy Prod Docs
on:
    push:
        branches:
            - develop
        paths:
            - "docs/**"
jobs:
    deploy:
        name: Deploy Staging Frontend
        runs-on: ubuntu-latest
        concurrency: deploy-group
        steps:
            - uses: actions/checkout@v4
            - uses: superfly/flyctl-actions/setup-flyctl@master
            - run:  flyctl deploy  -c fly.prod.toml --remote-only
              env:
                  FLY_API_TOKEN: ${{ secrets.FLY_STAGING_API_TOKEN }}
