name: Fly Deploy Staging Docs
on:
    push:
        branches:
            - develop
        paths:
            - "docs/**"
    workflow_dispatch:
jobs:
    deploy:
        name: Deploy Staging Docs
        runs-on: ubuntu-latest
        concurrency: deploy-group
        steps:
            - uses: actions/checkout@v4
            - uses: superfly/flyctl-actions/setup-flyctl@master
            - run:  cd docs && flyctl deploy  -c fly.toml --remote-only
              env:
                  FLY_API_TOKEN: ${{ secrets.FLY_API_TOKEN }}
