name: Fly Deploy Staging Frontend
on:
    push:
        branches:
            - develop
        paths:
            - "web-portal/frontend/**"
    workflow_dispatch:
jobs:
    deploy:
        name: Deploy Staging Frontend
        runs-on: ubuntu-latest
        concurrency: deploy-group
        steps:
            - uses: actions/checkout@v4
            - uses: superfly/flyctl-actions/setup-flyctl@master
            - run: cd web-portal/frontend && flyctl deploy  -c fly.toml --remote-only
              env:
                  FLY_API_TOKEN: ${{ secrets.FLY_API_TOKEN }}
