name: Fly Deploy Prod Frontend
on:
    push:
        branches:
            - master
        paths:
            - "web-portal/frontend/**"
jobs:
    deploy:
        name: Deploy Prod Frontend
        runs-on: ubuntu-latest
        concurrency: deploy-group
        steps:
            - uses: actions/checkout@v4
            - uses: superfly/flyctl-actions/setup-flyctl@master
            - run: cd web-portal/frontend && flyctl deploy  -c fly.prod.toml --remote-only
              env:
                  FLY_API_TOKEN: ${{ secrets.FLY_API_TOKEN }}
