name: Fly Deploy Staging Proxy
on:
    push:
        branches:
            - develop
        paths:
            - "gateway/**"
jobs:
    deploy:
        name: Deploy Staging Proxy
        runs-on: ubuntu-latest
        concurrency: deploy-group
        steps:
            - uses: actions/checkout@v4
            - uses: superfly/flyctl-actions/setup-flyctl@master
            - run: cd gateway && flyctl deploy --remote-only
              env:
                  FLY_API_TOKEN: ${{ secrets.FLY_STAGING_API_TOKEN }}
