name: Fly Deploy Prod Proxy
on:
    schedule:
        - cron: '0 */4 * * *'  # Runs every 4 hours
    push:
        branches:
            - master
        paths:
            - "gateway/**"
    workflow_dispatch:
jobs:
    deploy:
        name: Deploy Prod Proxy
        runs-on: ubuntu-latest
        concurrency: deploy-group
        steps:
            - uses: actions/checkout@v4
            - uses: superfly/flyctl-actions/setup-flyctl@master
            - run: cd gateway && flyctl deploy -c fly.prod.toml --remote-only
              env:
                  FLY_API_TOKEN: ${{ secrets.FLY_API_TOKEN }}
